services:

    command.project.create:
        class: eTraxis\SimpleBus\Projects\Handler\CreateProjectCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Projects\CreateProjectCommand }]
        arguments: [ "@validator", "@doctrine" ]

    command.project.update:
        class: eTraxis\SimpleBus\Projects\Handler\UpdateProjectCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Projects\UpdateProjectCommand }]
        arguments: [ "@validator", "@doctrine" ]

    command.project.delete:
        class: eTraxis\SimpleBus\Projects\Handler\DeleteProjectCommandHandler
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Projects\DeleteProjectCommand }]
        arguments: [ "@doctrine", "@security.authorization_checker" ]
