services:

    command.field.update.abstract:
        abstract: true
        class: eTraxis\SimpleBus\Fields\Handler\UpdateFieldCommandHandler
        arguments: [ "@validator", "@doctrine.orm.entity_manager", "@translator" ]

    command.field.update.number:
        parent: command.field.update.abstract
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Fields\UpdateNumberFieldCommand }]

    command.field.update.decimal:
        parent: command.field.update.abstract
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Fields\UpdateDecimalFieldCommand }]

    command.field.update.string:
        parent: command.field.update.abstract
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Fields\UpdateStringFieldCommand }]

    command.field.update.text:
        parent: command.field.update.abstract
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Fields\UpdateTextFieldCommand }]

    command.field.update.checkbox:
        parent: command.field.update.abstract
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Fields\UpdateCheckboxFieldCommand }]

    command.field.update.record:
        parent: command.field.update.abstract
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Fields\UpdateRecordFieldCommand }]

    command.field.update.list:
        parent: command.field.update.abstract
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Fields\UpdateListFieldCommand }]

    command.field.update.date:
        parent: command.field.update.abstract
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Fields\UpdateDateFieldCommand }]

    command.field.update.duration:
        parent: command.field.update.abstract
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Fields\UpdateDurationFieldCommand }]
