services:

    command.field.create.abstract:
        abstract: true
        class: eTraxis\SimpleBus\Fields\Handler\CreateFieldCommandHandler
        arguments: [ "@validator", "@doctrine.orm.entity_manager", "@translator" ]

    command.field.create.number:
        parent: command.field.create.abstract
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Fields\CreateNumberFieldCommand }]

    command.field.create.decimal:
        parent: command.field.create.abstract
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Fields\CreateDecimalFieldCommand }]

    command.field.create.string:
        parent: command.field.create.abstract
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Fields\CreateStringFieldCommand }]

    command.field.create.text:
        parent: command.field.create.abstract
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Fields\CreateTextFieldCommand }]

    command.field.create.checkbox:
        parent: command.field.create.abstract
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Fields\CreateCheckboxFieldCommand }]

    command.field.create.list:
        parent: command.field.create.abstract
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Fields\CreateListFieldCommand }]

    command.field.create.record:
        parent: command.field.create.abstract
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Fields\CreateRecordFieldCommand }]

    command.field.create.date:
        parent: command.field.create.abstract
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Fields\CreateDateFieldCommand }]

    command.field.create.duration:
        parent: command.field.create.abstract
        tags: [{ name: command_handler, handles: eTraxis\SimpleBus\Fields\CreateDurationFieldCommand }]
