checks:
    php:
        code_rating: true
        duplication: false

tools:
    external_code_coverage:
        timeout: 900
        runs: 2

filter:
    excluded_paths:
        - 'app/*'
        - 'src/AppBundle/DataFixtures/*'
        - 'tests/*'
        - 'web/*'
