language: php

php:
    - 7.0

env:
    - DB=mysql
    - DB=pgsql

sudo: false

before_install:
    - echo 'extension = ldap.so'                >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo 'default_charset = "UTF-8"'          >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo 'date.timezone = "Pacific/Auckland"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
    - cp app/config/travis/parameters.$DB.yml app/config/parameters.yml
    - composer install -n

before_script:
    - ./bin/console --env=test --no-interaction doctrine:database:create
    - ./bin/console --env=test --no-interaction doctrine:schema:create
    - ./bin/console --env=test --no-interaction doctrine:fixtures:load --fixtures=src/AppBundle/DataFixtures/Tests

script:
    - phpunit --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
