language: php

php:
    - 5.6
    - 7.0

env:
    - DB=mysql
    - DB=pgsql

sudo: false

addons:
    apt:
        packages:
        - php5-ldap

before_install:
    - echo 'extension = ldap.so'                >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo 'default_charset = "UTF-8"'          >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo 'date.timezone = "Pacific/Auckland"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
    - cp app/config/travis/parameters.$DB.yml app/config/parameters.yml
    - composer install -n

before_script:
    - ./bin/console --env=test --no-interaction doctrine:database:create
    - ./bin/console --env=test --no-interaction doctrine:schema:create
    - ./bin/console --env=test --no-interaction doctrine:fixtures:load --fixtures=src/AppBundle/DataFixtures/Tests

script:
    - if [[ "$(phpenv version-name)" == "7.0" ]]; then phpunit; fi
    - if [[ "$(phpenv version-name)" != "7.0" ]]; then phpunit --coverage-clover=coverage.clover; fi
    - if [[ "$(phpenv version-name)" != "7.0" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ "$(phpenv version-name)" != "7.0" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
