services:

    command.records.mark_as_read:
        class: eTraxis\CommandBus\Records\Handler\MarkRecordsAsReadCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\Records\MarkRecordsAsReadCommand }]
        arguments: [ "@doctrine.orm.entity_manager", "@security.token_storage" ]

    command.records.mark_as_unread:
        class: eTraxis\CommandBus\Records\Handler\MarkRecordsAsUnreadCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\Records\MarkRecordsAsUnreadCommand }]
        arguments: [ "@doctrine.orm.entity_manager", "@security.token_storage" ]

    command.records.postpone:
        class: eTraxis\CommandBus\Records\Handler\PostponeCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\Records\PostponeCommand }]
        arguments: [ "@doctrine.orm.entity_manager", "@security.authorization_checker", "@security.token_storage" ]

    command.records.resume:
        class: eTraxis\CommandBus\Records\Handler\ResumeCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\Records\ResumeCommand }]
        arguments: [ "@doctrine.orm.entity_manager", "@security.authorization_checker", "@security.token_storage" ]

    command.records.delete:
        class: eTraxis\CommandBus\Records\Handler\DeleteCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\Records\DeleteCommand }]
        arguments: [ "@doctrine.orm.entity_manager", "@security.authorization_checker" ]

    command.records.add_comment:
        class: eTraxis\CommandBus\Records\Handler\AddCommentCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\Records\AddCommentCommand }]
        arguments: [ "@doctrine.orm.entity_manager", "@security.authorization_checker", "@security.token_storage" ]
