services:

    command.listitem.create:
        class: eTraxis\CommandBus\ListItems\Handler\CreateListItemCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\ListItems\CreateListItemCommand }]
        arguments: [ "@validator", "@doctrine.orm.entity_manager" ]

    command.listitem.update:
        class: eTraxis\CommandBus\ListItems\Handler\UpdateListItemCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\ListItems\UpdateListItemCommand }]
        arguments: [ "@validator", "@doctrine.orm.entity_manager" ]

    command.listitem.delete:
        class: eTraxis\CommandBus\ListItems\Handler\DeleteListItemCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\ListItems\DeleteListItemCommand }]
        arguments: [ "@doctrine.orm.entity_manager", "@security.authorization_checker" ]
