services:

    command.user.register:
        class: eTraxis\CommandBus\Users\Handler\RegisterUserCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\Users\RegisterUserCommand }]
        arguments: [ "@logger", "@doctrine.orm.entity_manager", "%locale%", "%theme%" ]

    command.user.lock:
        class: eTraxis\CommandBus\Users\Handler\LockUserCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\Users\LockUserCommand }]
        arguments: [ "@logger", "@doctrine.orm.entity_manager", "%security_auth_attempts%", "%security_lock_time%" ]

    command.user.unlock:
        class: eTraxis\CommandBus\Users\Handler\UnlockUserCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\Users\UnlockUserCommand }]
        arguments: [ "@doctrine.orm.entity_manager" ]

    command.user.create:
        class: eTraxis\CommandBus\Users\Handler\CreateUserCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\Users\CreateUserCommand }]
        arguments: [ "@validator", "@doctrine.orm.entity_manager", "@etraxis.encoder" ]

    command.user.update:
        class: eTraxis\CommandBus\Users\Handler\UpdateUserCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\Users\UpdateUserCommand }]
        arguments: [ "@validator", "@doctrine.orm.entity_manager", "@security.token_storage" ]

    command.user.delete:
        class: eTraxis\CommandBus\Users\Handler\DeleteUserCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\Users\DeleteUserCommand }]
        arguments: [ "@doctrine.orm.entity_manager", "@security.authorization_checker" ]

    command.users.disable:
        class: eTraxis\CommandBus\Users\Handler\DisableUsersCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\Users\DisableUsersCommand }]
        arguments: [ "@doctrine.orm.entity_manager", "@security.token_storage" ]

    command.users.enable:
        class: eTraxis\CommandBus\Users\Handler\EnableUsersCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\Users\EnableUsersCommand }]
        arguments: [ "@doctrine.orm.entity_manager" ]

    command.settings.appearance:
        class: eTraxis\CommandBus\Users\Handler\SaveAppearanceCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\Users\SaveAppearanceCommand }]
        arguments: [ "@validator", "@doctrine.orm.entity_manager" ]

    command.password.set:
        class: eTraxis\CommandBus\Users\Handler\SetPasswordCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\Users\SetPasswordCommand }]
        arguments: [ "@translator", "@doctrine.orm.entity_manager", "@etraxis.encoder" ]

    command.password.forgot:
        class: eTraxis\CommandBus\Users\Handler\ForgotPasswordCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\Users\ForgotPasswordCommand }]
        arguments: [ "@doctrine.orm.entity_manager", "@etraxis.mailer" ]

    command.password.reset:
        class: eTraxis\CommandBus\Users\Handler\ResetPasswordCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\Users\ResetPasswordCommand }]
        arguments: [ "@translator", "@doctrine.orm.entity_manager", "@etraxis.encoder" ]

    command.users.add_groups:
        class: eTraxis\CommandBus\Users\Handler\AddGroupsCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\Users\AddGroupsCommand }]
        arguments: [ "@doctrine.orm.entity_manager" ]

    command.users.remove_groups:
        class: eTraxis\CommandBus\Users\Handler\RemoveGroupsCommandHandler
        tags: [{ name: tactician.handler, command: eTraxis\CommandBus\Users\RemoveGroupsCommand }]
        arguments: [ "@doctrine.orm.entity_manager" ]
