# Keep datatables sorted alphabetically.
services:

    etraxis.datatable.users:
        class: eTraxis\DataTables\UsersDataTable
        tags: [{ name: datatable, id: eTraxis:User }]
        arguments: [ "@doctrine.orm.entity_manager", "@translator" ]
