# Keep services sorted alphabetically.
services:

    etraxis.bbcode:
        class: eTraxis\Service\BBCode\BBCodeService

    etraxis.export:
        class: eTraxis\Service\Export\ExportService

    etraxis.mailer:
        class: eTraxis\Service\Mailer\MailerService
        arguments:
            - "@logger"
            - "@twig"
            - "@mailer"
            - "%mailfrom_address%"
            - "%mailfrom_name%"

    etraxis.records_cache:
        class: eTraxis\Service\RecordsCache\RecordsCacheService
        arguments:
            - "@cache.app"
