# Keep middlewares sorted alphabetically.
services:

    middleware.timing:
        class: eTraxis\CommandBus\Middleware\TimingMiddleware
        public: false
        arguments:
            - "@logger"

    middleware.validation:
        class: eTraxis\CommandBus\Middleware\ValidationMiddleware
        public: false
        arguments:
            - "@validator"
